apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: metrics-storage-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
  labels:
    strimzi.io/cluster: sumer
spec:
  replicas: {{ .Values.kafkaConnectReplicas }}
  bootstrapServers: sumer-kafka-brokers.kafka:9092
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "INFO"
  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-connect-metrics-config
        key: config-key         
  config:
    group.id: metrics-storage
    offset.storage.topic: metrics-storage-cluster-offsets
    config.storage.topic: metrics-storage-cluster-configs
    status.storage.topic: metrics-storage-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  build:
    output: # (2)
      type: docker
      image: 192.168.1.151:5000/metrics-storage-connect-cluster:tf
    plugins: # (3)
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.8.0.Final/debezium-connector-postgres-1.8.0.Final-plugin.tar.gz
