apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: sumer
  labels:
    strimzi.io/cluster: sumer
spec:
  kafka:
    replicas: {{ .Values.kafkaReplicas }}
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.0"
      inter.broker.protocol.version: "3.0"
    storage:
      type: persistent-claim
      size: 1Gi
    
  zookeeper:
    replicas: {{ .Values.zookeeperReplicas }}
    logging: 
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    storage:
      type: persistent-claim
      size: 1Gi
  
  entityOperator:
    userOperator: {}
    topicOperator: {}
      
