apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: postgres
  annotations:
    strimzi.io/use-connector-resources: "true"
  labels:
    strimzi.io/cluster: sumer
spec:
  replicas: {{ .Values.kafkaConnectReplicas }}
  bootstrapServers: sumer-kafka-brokers.kafka:9092
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "INFO"
  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-connect-metrics-config
        key: config-key         
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  # externalConfiguration:
  #   volumes:
  #     - name: connector-config
  #       configMap:
  #         name: metrics-storage-configmap
  build:
    output: # (2)
      type: docker
      image: 192.168.1.151:5000/connect-cluster:tf
      # pushSecret: my-registry-credentials
    plugins: # (3)
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.8.0.Final/debezium-connector-postgres-1.8.0.Final-plugin.tar.gz
            # sha512sum: 962a12151bdf9a5a30627eebac739955a4fd95a08d373b86bdcea2b4d0c27dd6e1edd5cb548045e115e33a9e69b1b2a352bee24df035a0447cb820077af00c03
