apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-postgres-connector
  labels:
    strimzi.io/cluster: sumer
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    # debezium.sink.type: pubsub
    # debezium.sink.pubsub.project.id: project-id
    connector.class: io.debezium.connector.postgresql.PostgresConnector
    offset.storage.file.filename: data/offsets.dat
    offset.flush.interval.ms: 0
    database.hostname: metrics-storage-postgresql.observability
    database.port: 5432
    database.user: utku
    database.password: utku
    database.dbname: example
    database.server.name: bankserver1
    table.include.list: bank.holding
    # plugin.name: pgoutput
