apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-postgres-connector
  labels:
    strimzi.io/cluster: metrics-storage-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    connector.class: io.debezium.connector.postgresql.PostgresConnector
    offset.flush.interval.ms: 0
    database.hostname: metrics-storage-postgresql.observability
    database.port: 5432
    database.user: postgres
    database.dbname: postgres
    database.server.name: bankserver1
    table.include.list: bank.holding
