apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bankserver1.bank.holding
  labels:
    strimzi.io/cluster: sumer
spec:
  partitions: {{ .Values.topicPartitions }}
  replicas: {{ min .Values.topicReplicas .Values.kafkaConnectReplicas }}
