apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ethereum-block-number
  labels:
    strimzi.io/cluster: sumer-kafka
spec:
  partitions: {{ .Values.topicPartitions }}
  replicas: {{ min .Values.topicReplicas .Values.kafkaReplicas }}
